### ISSUE TITLE
Wingpanel Icons/Text Are White Not Black

### ISSUE THREAD

**Issue by crutchcorn** [eOS-themes/Xenite#1]

**Comment by crutchcorn** [comment]
@Defman21, can I have help with this one? I cannot figure it out

**Comment by Defman21** [comment]
I'll try to find a solution(s) as far as I can. I'm working with some Dark stuff in the theme right now

**Comment by crutchcorn** [comment]
Quite alright. :) I just don't understand how they did this.

**Comment by Defman21** [comment]
Hmm, what is the reason to have these icons black? It should depends on the user's backround.

**Comment by crutchcorn** [comment]
No no, hang on and I'll show you

**Comment by crutchcorn** [comment]
![screenshot from 2015-04-20 15 11 45](https://cloud.githubusercontent.com/assets/9100169/7241646/a2d08ec0-e76f-11e4-8e92-2ce3fcef3fdc.png)
When a window is maximized the background is white, therefore the text should be back when maximized

**Comment by Defman21** [comment]
Ahh, you mean that... It is `org.pantheon.desktop.wingpanel.auto-adjust-alpha` option, I'll do some magic with that.

**Comment by crutchcorn** [comment]
Thanks. :/ I don't know enough about wingpanel to fix myself

**Comment by Defman21** [comment]
It's cannot be fixed through CSS files only. The default elementary theme have the same bug.

**Comment by crutchcorn** [comment]
How does evo-pop have black top text in that case?

**Comment by crutchcorn** [comment]
And I can package this into something else that will make everything all nice and pretty and work out. How do you do so?

**Comment by Defman21** [comment]
Ohh, evopop have a fix for that. I'll try to find in in the Evopop theme.

**Comment by Defman21** [comment]
No ideas how can I fix it. I'll ask on Reddit

**Comment by Defman21** [comment]
No ideas how can I fix it. I'll ask on Reddit

**Comment by crutchcorn** [comment]
Thanks! I have no ideas myself. I am lost

**Comment by crutchcorn** [comment]
I could talk to the evopop guys

**Comment by Defman21** [comment]
Wait please, I've asked about it here: http://www.reddit.com/r/elementaryos/comments/33adx4/change_wingpanel_color_when_the_panel_becomes/

**Comment by Defman21** [comment]
@crutchcorn please ask evopop devs about the issue. Seems like the /r/elementaryos community don't want to support designers :confused:

**Comment by crutchcorn** [comment]
I actually had, the said they just changed the text to white by doing so the normal gnome menu way... :/ I say we ask in the G+ community and tag Daniel Fore and others

**Comment by Defman21** [comment]
lol. Okay, we should ask them.

**Comment by crutchcorn** [comment]
You want to ask or shall I?

**Comment by Defman21** [comment]
You should. I don't have a time for asking about GTK theming now :(

**Comment by tom95** [comment]
Hey, to maybe give a little bit of help (only wrote the code for it, no idea about the theme part..), if you copy the elementary theme's default styles for wingpanel (which I assume can be found in apps.css, not sure) and then start adjusting from there, you should be pretty good.

One known limitation is that you have to use a plain background color, no gradients allowed. That's a result of a technical issue, we just pick the background color set by the theme and animate its alpha component, which we cannot do easily for background gradients or images.

**Comment by crutchcorn** [comment]
Yeah but that has a different background color than what we are trying to accomplish. Wouldn't that matter?

**Comment by Defman21** [comment]
![full width](http://i.imgur.com/qMntYql.png)
![not full width](http://i.imgur.com/dJDpcbE.png)

**Comment by crutchcorn** [comment]
YOU ARE MAGICAL HOW DID YOU DO THIS

**Comment by Defman21** [comment]
>if you copy the elementary theme's default styles for wingpanel (which I assume can be found in apps.css, not sure) and then start adjusting from there, you should be pretty good.

Thanks @tom95

**Comment by Defman21** [comment]
eOS make the panel transparent automatically so I just added some styles when panel aint transparent: https://github.com/eOS-themes/Xenite/blob/master/gtk-3.0/css/includes/wingpanel.css#L6
And added a color for both statutes (transparent/not transparent)
