### ISSUE TITLE
Weird Black Bar

### ISSUE THREAD

**Issue by crutchcorn** [eOS-themes/Xenite#16]
![screenshot from 2015-04-20 15 16 09](https://cloud.githubusercontent.com/assets/9100169/7241710/59298db6-e770-11e4-9ebe-257d0d00e1d9.png)

**Comment by Defman21** [comment]
AFAIK it's a Gnome 3.14 bug. I'll try to find a solution.

**Comment by Defman21** [comment]
Nothing can be done with my knowledge.

**Comment by crutchcorn** [comment]
Is it really? But it doesn't show in other GTK themes... Huh

**Comment by Defman21** [comment]
Other themes does not render the tab line in opacity style.

**Comment by crutchcorn** [comment]
True...

**Comment by Defman21** [comment]
Marked as unfixable issue. If someone find the solution - please describe it here.

**Comment by Defman21** [comment]
Can someone test it in other distros (not elementaryOS) with other versions of GTK? (3.12 or 3.16)

**Comment by crutchcorn** [comment]
I can try, yes. Give me a while to download and do all that stuff

**Comment by Defman21** [comment]
Noone interested to test that, thus we'll use elementary theme that should handle that. #71
