### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by Defman21** [eOS-themes/Xenite#20]

**Comment by crutchcorn** [comment]
I would like to do this after "The Cleaner" milestone. That can be 0.1 if you'd like

**Comment by Defman21** [comment]
Yep I like it.

**Comment by robby14** [comment]
what's the difference from the master branch and this "the cleaner"? Which one should I use? ( I guess the master one...)

**Comment by crutchcorn** [comment]
Use the main branch. "The Cleaner" may have bugs that the Master branch does not.

**Comment by Defman21** [comment]
They are both same. The cleaner will be removed in this week.

**Comment by Defman21** [comment]
I've removed `thecleaner` branch.

**Comment by crutchcorn** [comment]
Then is it almost time for 0.1?

**Comment by Defman21** [comment]
Nope! We don't have a good name for the theme.

**Comment by vinctux** [comment]
Maybe exOS?

**Comment by crutchcorn** [comment]
Let's move talk of names over to the name issue - however I dislike exOS

**Comment by Defman21** [comment]
Added a release.
