### ISSUE TITLE
Indicators menu items highlight is not 100% and indicator blue highlight background should be transparent

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/Xenite#45]
eXGTK:
![ekraanipilt 2015-04-22 22 34 23](https://cloud.githubusercontent.com/assets/7373586/7283540/f3f10466-e93f-11e4-9def-51f8afa2b0b1.png)

Should use elementary style:
![ekraanipilt 2015-04-22 22 34 41](https://cloud.githubusercontent.com/assets/7373586/7283545/fbd215d0-e93f-11e4-8df9-647558d8e260.png)

Also the blue selection box looks bad in my opinion.

**Comment by Defman21** [comment]
If you're meaning the padding for the popup items - I'm still looking how to fix that. And what is "the blue box"?

**Comment by TicTac7x** [comment]
Like in the Apps that you just removed, remove also from indicators, would look nicer and cleaner.

**Comment by Defman21** [comment]
#71
