### ISSUE TITLE
can't see top bar font clearly

### ISSUE THREAD

**Issue by xsjqqq123** [eOS-themes/Xenite#48]
Thanks of your work,this theme is beautiful.
I have a problem with it,it can't see top bar font clearly.
look like this:
![Image of problem](http://i1.tietuku.com/d78fa744d2dbcc64.png)

**Comment by Defman21** [comment]
It's fixed

**Comment by xsjqqq123** [comment]
I have tried again,it appeares another problem.
when I max some window ,the topbar'font can't see.
follow picture is the top-right of my screen:
![GitHub Logo](http://i1.tietuku.com/40f910519f7a0d46.png)

**Comment by Defman21** [comment]
I know about it, issue #1

**Comment by Defman21** [comment]
You can disable this feature: insert this command in the terminal `gsettings set org.pantheon.desktop.wingpanel auto-adjust-alpha false`

**Comment by xsjqqq123** [comment]
it works,but I want to have a const alpha value,what cant I do?thank you for your anser.

**Comment by Defman21** [comment]
`gsettings set org.pantheon.desktop.wingpanel background-alpha <alpha_value (0-1)>`

**Comment by Defman21** [comment]
If you still have any questions - ask it here.
