### ISSUE TITLE
Print Screen Does Not Flash Screen

### ISSUE THREAD

**Issue by crutchcorn** [eOS-themes/Xenite#49]
When you print screen in eOS it should make your screen flash to show that an image has been taken. With eXGTK, it does not

**Comment by Defman21** [comment]
Very hard to debug.

**Comment by crutchcorn** [comment]
I know. :P Why else do you think I waited this long to make a bug report

**Comment by Defman21** [comment]
This doesn't work in Loki with the default theme, so I'm going to close it in favor of #71
