### ISSUE TITLE
Top bar firefox

### ISSUE THREAD

**Issue by obloodo** [eOS-themes/Xenite#53]
Thank for your work, that's awewome,
but i have a question :  is it possible to make something for firefox top bar whose doesn't match with   Xenite theme ?
![firefox_xenite](https://cloud.githubusercontent.com/assets/5641295/7335002/7edc8904-eba4-11e4-8446-dfc64d38c68b.png)

good luck for your work.

**Comment by Defman21** [comment]
Why did you attach the screen with Paper theme?

**Comment by Defman21** [comment]
Anyway firefox uses GTK2 so...

**Comment by obloodo** [comment]
it was with the theme but ok thank's for answering .

**Comment by Defman21** [comment]
Anyway it looks fine to me.
![scr](http://i.imgur.com/cYjocfD.png)

**Comment by obloodo** [comment]
hum so weird, what version of firefox do you have ? i have the version 37

**Comment by Defman21** [comment]
Firefox 37.0.2. Did you forgot to change Metacity theme? I cannot do anything with Paper theme inside my theme.

**Comment by obloodo** [comment]
i know why , that was  because the theme was on my root folder  .themes not in /usr/share/themes
Thanks for your help

**Comment by Defman21** [comment]
Ohh man, the repo has a good documentation (thanks to @vinctux): https://github.com/eOS-themes/Xenite#stable
Please read the readme first and if you still have some issues you cannot solve - then you can create an issue :smiley: 
Best regards!

**Comment by vinctux** [comment]
Thanks :smiley: 
Will do the whole documentation (with pics) in the Wiki section tommorow.

**Comment by Defman21** [comment]
Lol, I didn't know we have a wiki :smiley:

**Comment by vinctux** [comment]
@Defman21 Just one OT thing - could you please start a [Gitter](https://gitter.im) chatroom on https://github.com/eOS-themes/Xenite/? Not all conversation (like this comment) needs to appear to the end user who wants to report something.

**Comment by Defman21** [comment]
Created.

**Comment by vinctux** [comment]
Could you please share the link?

**Comment by Defman21** [comment]
https://gitter.im/eOS-themes?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by vinctux** [comment]
Thanks.

**Comment by vinctux** [comment]
But I can't join - I'm not in the organization 'eOS-themes'.

**Comment by Defman21** [comment]
I've sent you an invite. Check your e-mail.

**Comment by vinctux** [comment]
Thanks so much!
