### ISSUE TITLE
Black battery icon

### ISSUE THREAD

**Issue by vinctux** [eOS-themes/Xenite#58]
I updated to the latest night build - this is the result:
![black-battery-icon](https://cloud.githubusercontent.com/assets/9408266/7338001/1cfe8ada-ec3e-11e4-9763-d6711eda6cec.png)

**Comment by Defman21** [comment]
Because of #1

**Comment by vinctux** [comment]
Then this issue is an inverse of #1?

**Comment by Defman21** [comment]
Yep. I cannot fix that. You can install Gnome Yosemite Icons to make all wingpanel icons in that color.

**Comment by vinctux** [comment]
Did exactly what they say and got this (for me even worse):
![black-battery-icon-2](https://cloud.githubusercontent.com/assets/9408266/7338122/09790f54-ec42-11e4-83ca-cabeb474949e.png)

**Comment by Defman21** [comment]
You forgot to install Numix Circle icons.

**Comment by vinctux** [comment]
Working!
