### ISSUE TITLE
A question about how to update

### ISSUE THREAD

**Issue by robby14** [eOS-themes/Xenite#60]
Hi, 
I've seen you've added automated installation,
what does that means? That I don't need anymore to do git pull origin master in the folder /usr/share/themes/Xenite to get the updates? Will it be updated all by itself?

**Comment by Defman21** [comment]
Nope, there's no auto-update. You can run `sudo sh -c "curl https://raw.githubusercontent.com/eOS-themes/Xenite/master/setup/install.sh | bash"` to update the theme or do `git pull origin mater` in the folder `/usr/share/themes/Xenite`.

**Comment by robby14** [comment]
ohh got it, thanks, maybe you could be clearer as you've been with the manual installation ;)

Thank you, 
cheer

**Comment by robby14** [comment]
I'm sorry but you said that there's no auto-update, but in the new installation details it's written that with that method will be auto-updated too! So?

**Comment by Defman21** [comment]
@vinctux updated the script, auto-update should works if you have installed cron.

**Comment by robby14** [comment]
oh okay, thanks
