### ISSUE TITLE
Window Control in Google Chrome

### ISSUE THREAD

**Issue by gravitano** [eOS-themes/Xenite#61]
![screenshot from 2015-04-29 13 45 45](https://cloud.githubusercontent.com/assets/5087538/7385818/29f0a1f8-ee76-11e4-915d-98da5a1f1132.png)

**Comment by gravitano** [comment]
Also, In other apps. Like Sublime text. Is this theme only support for built in eOS apps?

**Comment by crutchcorn** [comment]
No it is not.

**Comment by Defman21** [comment]
Are you using XFCE @gravitano?

**Comment by gravitano** [comment]
No, I am using elementary os freya.

**Comment by Defman21** [comment]
Does it happens in other apps?

**Comment by gravitano** [comment]
Yes, in sublime text, clementine and other apps that not built in from eOS.

**Comment by Defman21** [comment]
So something wrong with your installation... Try that.
```shell
sudo chown $USER:$USER -R /usr/share/themes/Xenite/
sudo chmod 777 -R /usr/share/themes/Xenite/
```

**Comment by gravitano** [comment]
Okay, will try it. Btw, I install it by cloning your repository to ~/.themes.

**Comment by Defman21** [comment]
Ohh... You must install it to /usr/share/themes/
~/.themes does not support GTK2 (eOS bug)

**Comment by Defman21** [comment]
Anyway why you didn't install it with the script we suggest?

**Comment by gravitano** [comment]
I've been tried using your suggest script. But, after the installation finished, the theme is not listed in eOS tweak. I've been moved the theme to `/usr/share/themes/` and now its working.

**Comment by Defman21** [comment]
The script works fine. Are you able to see Xenite folder in `/usr/share/themes/` after installation with the script?

**Comment by gravitano** [comment]
I don't know. I did not check it. But, when I try your instruction.

```
sudo chown $USER:$USER -R /usr/share/themes/Xenite/
sudo chmod 777 -R /usr/share/themes/Xenite/
```

I got `No such file or directory`. That's mean, the `Xenite` folder does exists, right ?

**Comment by Defman21** [comment]
does not exists.

**Comment by gravitano** [comment]
Oh yes, that's my bad. Thanks for the help!

**Comment by robby14** [comment]
Just two noob's question, I didn't use the script for 2 reason:
1. if I remember well that kind of script trigger at a certain time (maybe 4am o'clock?) what if my pc is shutted down?
2. I prefer not making run something more in background (I mean it's a further burden for the system, which is meant to be as light as possible)

These are just my assumptions, likely they're wrong, so can you answer to my doubts? :D thanks so much

**Comment by Defman21** [comment]
@vinctux answer plz.

**Comment by vinctux** [comment]
@robby14 
   1. Basically, the `install.sh` script is placing the `xenite.sh` script into the `/etc/cron.daily/` folder. All executable files in `/etc/cron.*` folders are generally executing every `x` period of time (so if in `/etc/cron.daily/` it should execute every day, `/etc/cron.weekly/` once every week, etc.).
   2. Generally, the update script doesn't take that much of system resources, but I'll add an option to opt-out.

As it seems, it particularly better to use the classical cronjob placing method, with `@reboot`. This will cause that at every startup of the (eOS) system, the `update.sh` script will run - it's no more important when (clock time), but when (event).

I'll make an update with corrected `cron` scripts.

**Comment by robby14** [comment]
@vinctux Thank you :)

**Comment by vinctux** [comment]
Now also this issue should be resolved :smile:

**Comment by robby14** [comment]
@vinctux Yes :D last curiosity, what if in the future I want to remove this script from being executed automatically? What should I do?

**Comment by Defman21** [comment]
`sudo crontab -e`
Remove `@reboot sudo /usr/share/themes/Xenite/setup/update.sh`
Then `sudo service cron stop && sudo service cron start`

**Comment by robby14** [comment]
@Defman21 Thank you, I have no more question XD

**Comment by vinctux** [comment]
Will be done.
