### ISSUE TITLE
No background highlighting on wingpanel date-time indicator

### ISSUE THREAD

**Issue by renearts** [eOS-themes/Xenite#62]
The background of the selected line/item on the date-time indicator on Wingpanel does not get highlighted. The text is highlighted thoug (turns from black->white) causing the selected item text to be nearly illegible.
Don't know whether it's related, but on Slingshot the selected item (when navigating with the keyboard) is also not visible. Only the first time Slingshot is launched it is visible (killing Slingshot and reopening it results in a highlighted background).

**Comment by Defman21** [comment]
Both of your reports aint our bugs at all. These problems are elementary OS problems :disappointed:

**Comment by renearts** [comment]
Are they? They work just fine on the default elementary theme.

**Comment by crutchcorn** [comment]
Does not play well with GTK themes aside from their own. Even their own themes show these issues occasionally. I've hit them myself.

**Comment by Defman21** [comment]
Because the default elementary theme contain some hacks for "hiding" these bugs. If the background of the selected item on the date-time indicator is not highlighted - it means that the popup (with calendar and other stuff) aint focused even if you think it's focused. The same for slingshot.

**Comment by renearts** [comment]
I see. Explains a lot. No probz, won't blame you guys then. You did an excellent job on this theme :) KUTGW!

**Comment by Defman21** [comment]
This is by design and this is how it will work in 0.4
