### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by tdtmusic** [eOS-themes/Xenite#63]
I'm on eOS Freya and I get this after running the install command:

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3186  100  3186    0     0   2504      0  0:00:01  0:00:01 --:--:--  2502
Installing dependencies . . .
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gtk2-engines-pixbuf is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
bash: line 37: canal: readonly variable
bash: line 38: syntax error near unexpected token `)'
bash: line 38: `    [Ss]* )'

Am I doing something wrong?!

**Comment by Defman21** [comment]
>Am I doing something wrong?!

Nope. Just an error in the script. @vinctux - deal with it, man :)

**Comment by vinctux** [comment]
Yes, it's a syntax error bug, as it seems. Will be fixed :)

**Comment by tchoulihan** [comment]
I'm getting this error too.

**Comment by tdtmusic** [comment]
Any update on this, guys?

**Comment by crutchcorn** [comment]
@vinctux is working on this. For now, you can simply 
`cd /usr/share/themes`
`git clone https://github.com/eOS-themes/Xenite.git`

**Comment by Defman21** [comment]
Your commands couldn't work. First run this `sudo chmod 777 -R /usr/share/themes/` to get permissions to do anything in this folder. Next you can run @crutchcorn commands.

**Comment by crutchcorn** [comment]
Gah. Whatever @Defman21 ;)

**Comment by tdtmusic** [comment]
Well it worked this way, but at this point there are too many issues with the theme to make it my default one. For example, the "tray" icons all seem to be the same size, except for the bluetooth icon, that one is huge. And yes, I'm using the post-install icon theme :) Also, the text (when clicking on that icon) is almost white on white, really hard to read...
Oh, and about the icons, I want them to be "identical", like in Numix circle, they're all in circles. But the Files icon is the plain old Finder icon, different from the others. And the settings icon is also different.

**Comment by Defman21** [comment]
This is not our icons. For this stuff you can ask about it for original developer. For other issues - you can file a bug if you sure it's our problem, not an eos distro problem. (Like that: https://github.com/eOS-themes/Xenite/issues/62)

**Comment by vinctux** [comment]
UPDATE: The development of the project has been discontinued (until eOS Loki 0.4 is out), anyway: if I find some spare time, I'll fix the scripts. But until then, the manual method is the "official" and only supported one.

**Comment by Defman21** [comment]
Since I've merged some pull requests that might fix the issue I want someone to test the installation process and report about any errors occurs during the process.

**Comment by vinctux** [comment]
The scripts should be fixed now. Give it another try ;)

**Comment by Defman21** [comment]
I forgot about this theme is existing :D

**Comment by vinctux** [comment]
Yes, a year moved by :D
