### ISSUE TITLE
Window controls are not present

### ISSUE THREAD

**Issue by oeus** [eOS-themes/Xenite#64]
Hi, first of all I would just like to say that this theme is absolutely amazing and is one of the best that I have found regarding the theming of OSX. 

The issue I have is regarding the window controls. The window controls show up in windows such as Firefox (my settings in elementary tweaks is OSX), but other windows do not show the window controls. 

Everything went fine during install and my icon pack I am using is Numix-Circle-Light. Did I do something wrong? I currently run Freya. 

Here are some screenshots of my desktop of Firefox (with the window controls) and another window selected (OSX window controls are absent from the upper right)

![window control](https://cloud.githubusercontent.com/assets/12521713/7717732/c9f99cea-fe6b-11e4-96c1-a4085854cc9d.png)

![window controls](https://cloud.githubusercontent.com/assets/12521713/7717737/dff17e5a-fe6b-11e4-8565-a805045bcb0e.png)

I sure do hope you can resolve this.

**Comment by Defman21** [comment]
Is it Luna?

**Comment by oeus** [comment]
My eOS? No, I am currently running Freya.

**Comment by Defman21** [comment]
Hmm, maybe something was wrong during installation...
Try to run these commands. Next re-change the theme in tweaks.
```bash
sudo chown 777 -R /usr/share/themes/ && sudo rm- r /usr/share/themes/Xenite && cd /usr/share/themes/ && git clone https://github.com/eOS-themes/Xenite.git
```

**Comment by oeus** [comment]
I get an error when I enter in your command. Am I missing something?

sudo: rm-: command not found

**Comment by Defman21** [comment]
Oh, excuse me. 
```bash
sudo chown 777 -R /usr/share/themes/ && sudo rm -r /usr/share/themes/Xenite/ && cd /usr/share/themes/ && git clone https://github.com/eOS-themes/Xenite.git
```

**Comment by oeus** [comment]
Forgive me, but I installed Xenite-master in ~.themes under Home, because it worked best. The script used to install it automatically for me did not work. My code is:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3186  100  3186    0     0   8786      0 --:--:-- --:--:-- --:--:--  8776
Installing dependencies . . .
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gtk2-engines-pixbuf is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 248 not upgraded.
bash: line 37: canal: readonly variable
bash: line 38: syntax error near unexpected token `)'
bash: line 38: `    [Ss]* )'

**Comment by Defman21** [comment]
Please do not install anything of this type of contribution to eOS under your home folder. Freya has some bugs with the themes installed under ~/.themes such as your bug. We know about an error in installation and @vinctux (iirc) will fix that as far as he can. Just extract `Xenite` folder in the zip file you downloaded (I sure it's Xenite-master archive generated by GitHub) to `/usr/share/themes/` and remove the theme from ~/.themes

**Comment by oeus** [comment]
Alright, I will do so.

**Comment by oeus** [comment]
Alright, after downloading it and unzipping it into /usr/share/themes there has been no change. Terminal and Firefox have the controls, but basically every other program does not.

![screenshot from 2015-05-20 18 16 20](https://cloud.githubusercontent.com/assets/12521713/7738619/5dee7618-ff1c-11e4-8062-acb25ce1b625.png)

**Comment by oeus** [comment]
Am I the only one with this issue?

**Comment by oeus** [comment]
Oh, by the way the upgrade absolutely craps on my computer. After I upgrade, when I restart I get really bad lag through boot, login, everything. I had to wipe and reinstall elementary two times :(

**Comment by Defman21** [comment]
Your file manager is a bit different than my. 
Please run this command: `pantheon-files --version` and show me the output.

**Comment by oeus** [comment]
Oh, I use Nautilus.

**Comment by oeus** [comment]
Alright, some stuff happened to my os, I had to do a clean install of eOS again.
Here is what I did different this time (first time I installed manually)

This time I reinstalled eOS, got everything running (elementary-tweaks, etc..), but this time I used the script that auto-installed the theme and I also installed the Numix Icon Theme with your post-install script. The post-install script worked, but the regular install script did not. I instead installed the Xenite theme with these commands highlighted in the screenshot below from a previous issue.

![screenshot from 2015-05-21 18 30 56](https://cloud.githubusercontent.com/assets/12521713/7761250/2efd7138-ffe9-11e4-9e7d-64bb9797c12d.png)

This succeeded at installing the Xenite theme into elementary-tweaks. I proceeded to use it, but still no cookie :(

![screenshot from 2015-05-21 18 35 18](https://cloud.githubusercontent.com/assets/12521713/7761263/50547b10-ffe9-11e4-98a3-b2bed6917400.png)

**Comment by bil-elmoussaoui** [comment]
Try changing the windows controls to elementary ? @oeus  or something else.

**Comment by oeus** [comment]
@bil-elmoussaoui Nope, already tried that. Same results :/

**Comment by Defman21** [comment]
```bash
ls /usr/share/themes/Xenite/gtk-3.0/css/window-controls/ && cat /usr/share/themes/Xenite/gtk-3.0/css/window-control.css
```

**Comment by oeus** [comment]
@Defman21 Here is the response interminal to your command:


justin@Omniscience:~$ ls /usr/share/themes/Xenite/gtk-3.0/css/window-controls/ && cat /usr/share/themes/Xenite/gtk-3.0/css/window-control.css
close_prelight.svg  close_unfocused.svg    maximize.svg             min_prelight.svg  min_unfocused.svg    window-maximize-symbolic.svg
close_pressed.svg   maximize_prelight.svg  maximize_unfocused1.svg  min_pressed.svg   titlebar_button.svg  window-restore-symbolic.svg
close.svg           maximize_pressed.svg   maximize_unfocused.svg   min.svg           unfocused_dark.svg
.titlebar .right .titlebutton,
.titlebar .left .titlebutton {
	color: transparent;
	background-position: center;
	background-repeat: no-repeat;
	background-color: transparent;
  box-shadow: none;
	border: none;
}

.titlebar .titlebutton,
.titlebar .titlebutton:backdrop,
.titlebar .titlebutton:backdrop:hover,
.titlebar .titlebutton:active,
.titlebar .titlebutton:hover {
	border: none;
	box-shadow: none;
}

/* Evopop style */
.titlebar .button.titlebutton {
  padding: 8px;
  padding-left: 4px;
  padding-right: 4px;
}


/* Set correct layout with
	gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <':minimize,maximize,close'>}" for buttons on the right
	or
	gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <'close,maximize,minimize:'>}"
	for buttons on the left */

/* minimize */
.titlebar .left .titlebutton.minimize,
.titlebar .right .titlebutton.minimize {
	background-image: url('window-controls/min.svg');
}

.titlebar .left .titlebutton.minimize:backdrop,
.titlebar .right .titlebutton.minimize:backdrop {
	background-image: url('window-controls/min_unfocused.svg');
	-gtk-image-effect: dim;
}

.titlebar .left .titlebutton.minimize:hover,
.titlebar .right .titlebutton.minimize:hover {
	background-image: url('window-controls/min_prelight.svg');
}

.titlebar .left .titlebutton.minimize:active,
.titlebar .right .titlebutton.minimize:active {
	background-image: url('window-controls/min_pressed.svg');
}

/* close */
.titlebar .left .titlebutton.close,
.titlebar .right .titlebutton.close {
	background-image: url('window-controls/close.svg');
}

.titlebar .left .titlebutton.close:backdrop,
.titlebar .right .titlebutton.close:backdrop {
	background-image: url('window-controls/close_unfocused.svg');
	-gtk-image-effect: dim;
}

.titlebar .left .titlebutton.close:hover,
.titlebar .right .titlebutton.close:hover {
	background-image: url('window-controls/close_prelight.svg');
}

.titlebar .left .titlebutton.close:active,
.titlebar .right .titlebutton.close:active {
	background-image: url('window-controls/close_pressed.svg');
}


/* maximize */
.titlebar .left .titlebutton.maximize,
.titlebar .right .titlebutton.maximize {
	background-image: url('window-controls/maximize.svg');
}

.titlebar .left .titlebutton.maximize:backdrop,
.titlebar .right .titlebutton.maximize:backdrop {
	background-image: url('window-controls/maximize_unfocused.svg');
	-gtk-image-effect: dim;
}

.titlebar .left .titlebutton.maximize:hover,
.titlebar .right .titlebutton.maximize:hover {
	background-image: url('window-controls/maximize_prelight.svg');
}

.titlebar .left .titlebutton.maximize:active,
.titlebar .right .titlebutton.maximize:active {
	background-image: url('window-controls/maximize_pressed.svg');
}

**Comment by oeus** [comment]
Hey, I got it all figured out. The theme works when I run
sudo apt-get upgrade && sudo apt-get dist-upgrade
but my system lags like crap, so I am just going to switch back to ubuntu nd figure out how to skin it over there :(
