### ISSUE TITLE
Error on uninstall

### ISSUE THREAD

**Issue by kingogames** [eOS-themes/Xenite#65]
anthonys@anthonys-Aspire-S3:/usr/share/themes$ sudo sh -c "curl https://raw.githubusercontent.com/eOS-themes/Xenite/master/setup/uninstall.sh | bash"
[sudo] password for anthonys: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1434  100  1434    0     0   1297      0  0:00:01  0:00:01 --:--:--  1298
Uninstalling dependencies . . .
bash: line 33: syntax error: unexpected end of file

**Comment by Defman21** [comment]
NOTE: Current setup scripts are full of bugs and must be rewritten - hopefully soon. Please consider using the manual way of installing Xenite. Well, uninstall scripts are full of bugs too. If you want to remove Xenite - just delete `/usr/share/themes/Xenite` folder and remove `@reboot /usr/share/themes/Xenite/setup/update.sh` from your crontab (`sudo crontab -e`)

**Comment by vinctux** [comment]
If I find some spare time, I'll fix the scripts. But until then, the manual method is the "official" and only supported one.
