### ISSUE TITLE
Wingpanel themes some icons white and others black

### ISSUE THREAD

**Issue by ezeeyahoo** [eOS-themes/Xenite#69]
What all tools etc I need to have on my machine to solve GTK3 bugs. I want to try given that I am a professional developer but new to this..

Bug: when I use GTK+ theme on EOS Freya, Wingpanel doesn't theme icons properly- Slingshot launcher, clock, battery(when charging), bluetooth indicator are in black rest tray icon are in white. They must be white for the wallpaper I have selected.
![screenshot from 2015-09-26 15 14 37](https://cloud.githubusercontent.com/assets/3622762/10116894/5f9a7dcc-6461-11e5-8412-f40ab27714ff.png)

Thanks,
Eshant

**Comment by crutchcorn** [comment]
A lot of a GTK theme is made in CSS-like code. You might need GTK Inspector to help you out. I'd say, tweak around with stuff - look at our issues and try to help out if you can!

**Comment by Defman21** [comment]
There is no way to detect what type of wallpaper you're using (bright/dark) and there is no way to change the colors depends on the wallpaper.
About tools... I used [GTK Inspector](https://wiki.gnome.org/Projects/GTK%2B/Inspector) to debug some GTK3 apps that I want to customize. I don't know is there an another tool to debug GTK3 apps, but I guess the answer is "no".

**Comment by ezeeyahoo** [comment]
What I have understood is white icons are because of icon theme I choose but for Xenite default font and icon color is black though I am still doubtful about battery icon which become white while discharging remains black when charging or charged. So for next release there should be two theme Xenite light and Xenite dark.
For now I have worked on a workaround i.e :-
1) I have changed dconf-editor -> pantheon -> desktop -> wingpanel -> auto-adjust to 'false'
2) Now opacity to 0.6
3) Icon theme Numix-Circle-Light which gives all dark icon
Result:-
![screenshot from 2015-09-27 15 18 41](https://cloud.githubusercontent.com/assets/3622762/10122137/18219d16-652b-11e5-9eb8-038132afd210.png)

**Comment by Defman21** [comment]
I'm not sure I'll be interested in creating a dark version of Xenite. I think I'll create 2 simple CSS files that you could use if you want to see the white or black text in wingpanel

**Comment by ezeeyahoo** [comment]
It sounds fine but there won't be much to do I guess, for separate theme same CSS with font color light and few system icons bluetooth, power-manager(charging and charged) and power. Also bluetooth indicator looks larger than rest, it can also be fixed.

**Comment by vinctux** [comment]
@Defman21 Maybe, when Loki is out (which won't apparently happen in near future), we could have an own PPA for Xenite - and as you choose with Numix which subtheme you want to have enabled, so we could make it w/ Xenite. I'm saying this because I don't think I've got the interest to write all those setup scripts from scratch again - maybe I'll do it, but it's definitely not a permanent solution (PPA is way better for this purpose). PPA would solve the install/remove/choose process much easier and w/o the problems as themeon.

**Comment by Defman21** [comment]
Hmm, ppa is a good idea. But I don't have any experience in creating a PPA repository, so... yeah, I have to learn how to use it :stuck_out_tongue:

**Comment by vinctux** [comment]
Maybe this is a good place to start https://askubuntu.com/a/71516

**Comment by Defman21** [comment]
Thanks for the link. I'll read this once I'll have a free time for it :)

**Comment by vinctux** [comment]
I'll do the same. `permanence(PPA) >>> permanence(themeon)`  :D

**Comment by ezeeyahoo** [comment]
gr8 :)

**Comment by Defman21** [comment]
Wingpanel is now auto-adjusting the color of indicators depends on the wallpaper.
