### ISSUE TITLE
ugly files selection

### ISSUE THREAD

**Issue by robby14** [eOS-themes/Xenite#7]
![screenshot from 2015-04-17 12 26 46](https://cloud.githubusercontent.com/assets/11992666/7201544/c39e80c6-e508-11e4-888e-270f72d1a6ae.png)
![screenshot from 2015-04-17 12 20 17](https://cloud.githubusercontent.com/assets/11992666/7201543/c39e3f9e-e508-11e4-9fda-06482599bf5b.png)

The latter is from elementary. I guess the first one is kind of ugly to see

**Comment by crutchcorn** [comment]
I agree.. This is something I haven't done before so it might take a bit to figure that one out...

**Comment by Defman21** [comment]
2 hard 4 me. I'll try to find what styling it

**Comment by crutchcorn** [comment]
I can look into it more another day

**Comment by Defman21** [comment]
Will do, please. Assigned you.

**Comment by crutchcorn** [comment]
KK

**Comment by Defman21** [comment]
Just to help you: search for GtkIconView in Google and in the code. This widget display icons. And I cannot find how can I change anything in the object. Most of the properties are for GtkIconView itself, not for the children (so styling may be very hard, I think)

**Comment by Defman21** [comment]
#71
