### ISSUE TITLE
Very hard to see Geary mail list

### ISSUE THREAD

**Issue by ezeeyahoo** [eOS-themes/Xenite#70]
Please check 
![screenshot from 2015-11-02 00 28 28](https://cloud.githubusercontent.com/assets/3622762/10870766/c5714fbe-80f8-11e5-978b-f0eafef83868.png)
Can you tell me where or which file I have to look in to fix this issue? I have spend time doing hit and trial but couldn't figure out any change happening.

Edit 1: There is no debug inside org>gtk>settings>debug in Freya to enable gtkinspector..I don't know how to get debug in the hierarchy.
I have included apps.css under gtkwidgets.css in the fashion done in default theme but haven't seen any change

**Comment by Defman21** [comment]
To get the debugging app inside a GTK3 app, you have to run the app via the terminal with a special flag (something like `GTK_DEBUG=true` or something like this, don't remember now, better to google it), then press Ctrl+Shift+D IIRC.

**Comment by Defman21** [comment]
#71
